name: "FAP: Build and Release"
on:
  push:
    branches:
      - main
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: "ufbt: Build and publish release"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          # Set to 'release' to build for latest published release version
          sdk-channel: rc
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}-${{ steps.build-app.outputs.suffix }}
        run: |
          gh release create "$tag" \
            --repo="${{ github.repository }}" \
            --title="${{ github.event.repository.name }} ${{ steps.build-app.outputs.suffix }}" \
            ${{ steps.build-app.outputs.fap-artifacts }}
